QB:

name: JavaGoat-WhatsApp-Bor

workflow dispatch

schedul

step

utnanta latest

name: Checkout Code uses actions/checkout

name: Setup Nod

нек аспапаљетиp-pode@va

node-version 20

name Install Dependencies

-name: Start Al Bot

run nom start

FIRERASE URL SEE secres FTREMASTURI 31
